# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'SwiftDemoProject' do
  # Pods for SwiftDemoProject
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxSwiftExt'
  pod 'PKHUD', '~> 5.0'
  pod 'Moya/RxSwift', '~> 12.0'
end

target 'SwiftDemoProjectTests' do
  # Pods for SwiftDemoProjectTests
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Moya/RxSwift', '~> 12.0'
end
