# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftDemoProject' do
  use_frameworks!

  # Pods for SwiftDemoProject
  pod 'Alamofire',    '~> 4.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxSwiftExt'
  pod 'PKHUD', '~> 5.0'
end
